<option value="Afghanistan"><?php echo app('translator')->get("Afghanistan"); ?></option>
<option value="Åland Islands"><?php echo app('translator')->get("Åland Islands"); ?></option>
<option value="Albania"><?php echo app('translator')->get("Albania"); ?></option>
<option value="Algeria"><?php echo app('translator')->get("Algeria"); ?></option>
<option value="American Samoa"><?php echo app('translator')->get("American Samoa"); ?></option>
<option value="Andorra"><?php echo app('translator')->get("Andorra"); ?></option>
<option value="Angola"><?php echo app('translator')->get("Angola"); ?></option>
<option value="Anguilla"><?php echo app('translator')->get("Anguilla"); ?></option>
<option value="Antarctica"><?php echo app('translator')->get("Antarctica"); ?></option>
<option value="Antigua and Barbuda"><?php echo app('translator')->get("Antigua and Barbuda"); ?></option>
<option value="Argentina"><?php echo app('translator')->get("Argentina"); ?></option>
<option value="Armenia"><?php echo app('translator')->get("Armenia"); ?></option>
<option value="Aruba"><?php echo app('translator')->get("Aruba"); ?></option>
<option value="Australia"><?php echo app('translator')->get("Australia"); ?></option>
<option value="Austria"><?php echo app('translator')->get("Austria"); ?></option>
<option value="Azerbaijan"><?php echo app('translator')->get("Azerbaijan"); ?></option>
<option value="Bahamas"><?php echo app('translator')->get("Bahamas"); ?></option>
<option value="Bahrain"><?php echo app('translator')->get("Bahrain"); ?></option>
<option value="Bangladesh"><?php echo app('translator')->get("Bangladesh"); ?></option>
<option value="Barbados"><?php echo app('translator')->get("Barbados"); ?></option>
<option value="Belarus"><?php echo app('translator')->get("Belarus"); ?></option>
<option value="Belgium"><?php echo app('translator')->get("Belgium"); ?></option>
<option value="Belize"><?php echo app('translator')->get("Belize"); ?></option>
<option value="Benin"><?php echo app('translator')->get("Benin"); ?></option>
<option value="Bermuda"><?php echo app('translator')->get("Bermuda"); ?></option>
<option value="Bhutan"><?php echo app('translator')->get("Bhutan"); ?></option>
<option value="Bolivia, Plurinational State of bolivia"><?php echo app('translator')->get("Bolivia, Plurinational State of bolivia"); ?></option>
<option value="Bosnia and Herzegovina"><?php echo app('translator')->get("Bosnia and Herzegovina"); ?></option>
<option value="Botswana"><?php echo app('translator')->get("Botswana"); ?></option>
<option value="Bouvet Island"><?php echo app('translator')->get("Bouvet Island"); ?></option>
<option value="Brazil"><?php echo app('translator')->get("Brazil"); ?></option>
<option value="British Indian Ocean Territory"><?php echo app('translator')->get("British Indian Ocean Territory"); ?></option>
<option value="Brunei Darussalam"><?php echo app('translator')->get("Brunei Darussalam"); ?></option>
<option value="Bulgaria"><?php echo app('translator')->get("Bulgaria"); ?></option>
<option value="Burkina Faso"><?php echo app('translator')->get("Burkina Faso"); ?></option>
<option value="Burundi"><?php echo app('translator')->get("Burundi"); ?></option>
<option value="Cambodia"><?php echo app('translator')->get("Cambodia"); ?></option>
<option value="Cameroon"><?php echo app('translator')->get("Cameroon"); ?></option>
<option value="Canada"><?php echo app('translator')->get("Canada"); ?></option>
<option value="Cape Verde"><?php echo app('translator')->get("Cape Verde"); ?></option>
<option value="Cayman Islands"><?php echo app('translator')->get("Cayman Islands"); ?></option>
<option value="Central African Republic"><?php echo app('translator')->get("Central African Republic"); ?></option>
<option value="Chad"><?php echo app('translator')->get("Chad"); ?></option>
<option value="Chile"><?php echo app('translator')->get("Chile"); ?></option>
<option value="China"><?php echo app('translator')->get("China"); ?></option>
<option value="Christmas Island"><?php echo app('translator')->get("Christmas Island"); ?></option>
<option value="Cocos (Keeling) Islands"><?php echo app('translator')->get("Cocos (Keeling) Islands"); ?></option>
<option value="Colombia"><?php echo app('translator')->get("Colombia"); ?></option>
<option value="Comoros"><?php echo app('translator')->get("Comoros"); ?></option>
<option value="Congo"><?php echo app('translator')->get("Congo"); ?></option>
<option value="Congo, The Democratic Republic of the Congo"><?php echo app('translator')->get("Congo, The Democratic Republic of the Congo"); ?></option>
<option value="Cook Islands"><?php echo app('translator')->get("Cook Islands"); ?></option>
<option value="Costa Rica"><?php echo app('translator')->get("Costa Rica"); ?></option>
<option value="Cote d'Ivoire"><?php echo app('translator')->get("Cote d'Ivoire"); ?></option>
<option value="Croatia"><?php echo app('translator')->get("Croatia"); ?></option>
<option value="Cuba"><?php echo app('translator')->get("Cuba"); ?></option>
<option value="Cyprus"><?php echo app('translator')->get("Cyprus"); ?></option>
<option value="Czech Republic"><?php echo app('translator')->get("Czech Republic"); ?></option>
<option value="Denmark"><?php echo app('translator')->get("Denmark"); ?></option>
<option value="Djibouti"><?php echo app('translator')->get("Djibouti"); ?></option>
<option value="Dominica"><?php echo app('translator')->get("Dominica"); ?></option>
<option value="Dominican Republic"><?php echo app('translator')->get("Dominican Republic"); ?></option>
<option value="Ecuador"><?php echo app('translator')->get("Ecuador"); ?></option>
<option value="Egypt"><?php echo app('translator')->get("Egypt"); ?></option>
<option value="El Salvador"><?php echo app('translator')->get("El Salvador"); ?></option>
<option value="Equatorial Guinea"><?php echo app('translator')->get("Equatorial Guinea"); ?></option>
<option value="Eritrea"><?php echo app('translator')->get("Eritrea"); ?></option>
<option value="Estonia"><?php echo app('translator')->get("Estonia"); ?></option>
<option value="Ethiopia"><?php echo app('translator')->get("Ethiopia"); ?></option>
<option value="Falkland Islands (Malvinas)"><?php echo app('translator')->get("Falkland Islands (Malvinas)"); ?></option>
<option value="Faroe Islands"><?php echo app('translator')->get("Faroe Islands"); ?></option>
<option value="Fiji"><?php echo app('translator')->get("Fiji"); ?></option>
<option value="Finland"><?php echo app('translator')->get("Finland"); ?></option>
<option value="France"><?php echo app('translator')->get("France"); ?></option>
<option value="French Guiana"><?php echo app('translator')->get("French Guiana"); ?></option>
<option value="French Polynesia"><?php echo app('translator')->get("French Polynesia"); ?></option>
<option value="French Southern Territories"><?php echo app('translator')->get("French Southern Territories"); ?></option>
<option value="Gabon"><?php echo app('translator')->get("Gabon"); ?></option>
<option value="Gambia"><?php echo app('translator')->get("Gambia"); ?></option>
<option value="Georgia"><?php echo app('translator')->get("Georgia"); ?></option>
<option value="Germany"><?php echo app('translator')->get("Germany"); ?></option>
<option value="Ghana"><?php echo app('translator')->get("Ghana"); ?></option>
<option value="Gibraltar"><?php echo app('translator')->get("Gibraltar"); ?></option>
<option value="Greece"><?php echo app('translator')->get("Greece"); ?></option>
<option value="Greenland"><?php echo app('translator')->get("Greenland"); ?></option>
<option value="Grenada"><?php echo app('translator')->get("Grenada"); ?></option>
<option value="Guadeloupe"><?php echo app('translator')->get("Guadeloupe"); ?></option>
<option value="Guam"><?php echo app('translator')->get("Guam"); ?></option>
<option value="Guatemala"><?php echo app('translator')->get("Guatemala"); ?></option>
<option value="Guernsey"><?php echo app('translator')->get("Guernsey"); ?></option>
<option value="Guinea"><?php echo app('translator')->get("Guinea"); ?></option>
<option value="Guinea-Bissau"><?php echo app('translator')->get("Guinea-Bissau"); ?></option>
<option value="Guyana"><?php echo app('translator')->get("Guyana"); ?></option>
<option value="Haiti"><?php echo app('translator')->get("Haiti"); ?></option>
<option value="Heard Island and Mcdonald Islands"><?php echo app('translator')->get("Heard Island and Mcdonald Islands"); ?></option>
<option value="Holy See (Vatican City State)"><?php echo app('translator')->get("Holy See (Vatican City State)"); ?></option>
<option value="Honduras"><?php echo app('translator')->get("Honduras"); ?></option>
<option value="Hong Kong"><?php echo app('translator')->get("Hong Kong"); ?></option>
<option value="Hungary"><?php echo app('translator')->get("Hungary"); ?></option>
<option value="Iceland"><?php echo app('translator')->get("Iceland"); ?></option>
<option value="India"><?php echo app('translator')->get("India"); ?></option>
<option value="Indonesia"><?php echo app('translator')->get("Indonesia"); ?></option>
<option value="Iran, Islamic Republic of Persian Gulf"><?php echo app('translator')->get("Iran, Islamic Republic of Persian Gulf"); ?></option>
<option value="Iraq"><?php echo app('translator')->get("Iraq"); ?></option>
<option value="Ireland"><?php echo app('translator')->get("Ireland"); ?></option>
<option value="Isle of Man"><?php echo app('translator')->get("Isle of Man"); ?></option>
<option value="Israel"><?php echo app('translator')->get("Israel"); ?></option>
<option value="Italy"><?php echo app('translator')->get("Italy"); ?></option>
<option value="Jamaica"><?php echo app('translator')->get("Jamaica"); ?></option>
<option value="Japan"><?php echo app('translator')->get("Japan"); ?></option>
<option value="Jersey"><?php echo app('translator')->get("Jersey"); ?></option>
<option value="Jordan"><?php echo app('translator')->get("Jordan"); ?></option>
<option value="Kazakhstan"><?php echo app('translator')->get("Kazakhstan"); ?></option>
<option value="Kenya"><?php echo app('translator')->get("Kenya"); ?></option>
<option value="Kiribati"><?php echo app('translator')->get("Kiribati"); ?></option>
<option value="Korea, Democratic People's Republic of Korea"><?php echo app('translator')->get("Korea, Democratic People's Republic of Korea"); ?></option>
<option value="Korea, Republic of South Korea"><?php echo app('translator')->get("Korea, Republic of South Korea"); ?></option>
<option value="Kosovo"><?php echo app('translator')->get("Kosovo"); ?></option>
<option value="Kuwait"><?php echo app('translator')->get("Kuwait"); ?></option>
<option value="Kyrgyzstan"><?php echo app('translator')->get("Kyrgyzstan"); ?></option>
<option value="Laos"><?php echo app('translator')->get("Laos"); ?></option>
<option value="Latvia"><?php echo app('translator')->get("Latvia"); ?></option>
<option value="Lebanon"><?php echo app('translator')->get("Lebanon"); ?></option>
<option value="Lesotho"><?php echo app('translator')->get("Lesotho"); ?></option>
<option value="Liberia"><?php echo app('translator')->get("Liberia"); ?></option>
<option value="Libyan Arab Jamahiriya"><?php echo app('translator')->get("Libyan Arab Jamahiriya"); ?></option>
<option value="Liechtenstein"><?php echo app('translator')->get("Liechtenstein"); ?></option>
<option value="Lithuania"><?php echo app('translator')->get("Lithuania"); ?></option>
<option value="Luxembourg"><?php echo app('translator')->get("Luxembourg"); ?></option>
<option value="Macao"><?php echo app('translator')->get("Macao"); ?></option>
<option value="Macedonia"><?php echo app('translator')->get("Macedonia"); ?></option>
<option value="Madagascar"><?php echo app('translator')->get("Madagascar"); ?></option>
<option value="Malawi"><?php echo app('translator')->get("Malawi"); ?></option>
<option value="Malaysia"><?php echo app('translator')->get("Malaysia"); ?></option>
<option value="Maldives"><?php echo app('translator')->get("Maldives"); ?></option>
<option value="Mali"><?php echo app('translator')->get("Mali"); ?></option>
<option value="Malta"><?php echo app('translator')->get("Malta"); ?></option>
<option value="Marshall Islands"><?php echo app('translator')->get("Marshall Islands"); ?></option>
<option value="Martinique"><?php echo app('translator')->get("Martinique"); ?></option>
<option value="Mauritania"><?php echo app('translator')->get("Mauritania"); ?></option>
<option value="Mauritius"><?php echo app('translator')->get("Mauritius"); ?></option>
<option value="Mayotte"><?php echo app('translator')->get("Mayotte"); ?></option>
<option value="Mexico"><?php echo app('translator')->get("Mexico"); ?></option>
<option value="Micronesia, Federated States of Micronesia"><?php echo app('translator')->get("Micronesia, Federated States of Micronesia"); ?></option>
<option value="Moldova"><?php echo app('translator')->get("Moldova"); ?></option>
<option value="Monaco"><?php echo app('translator')->get("Monaco"); ?></option>
<option value="Mongolia"><?php echo app('translator')->get("Mongolia"); ?></option>
<option value="Montenegro"><?php echo app('translator')->get("Montenegro"); ?></option>
<option value="Montserrat"><?php echo app('translator')->get("Montserrat"); ?></option>
<option value="Morocco"><?php echo app('translator')->get("Morocco"); ?></option>
<option value="Mozambique"><?php echo app('translator')->get("Mozambique"); ?></option>
<option value="Myanmar"><?php echo app('translator')->get("Myanmar"); ?></option>
<option value="Namibia"><?php echo app('translator')->get("Namibia"); ?></option>
<option value="Nauru"><?php echo app('translator')->get("Nauru"); ?></option>
<option value="Nepal"><?php echo app('translator')->get("Nepal"); ?></option>
<option value="Netherlands"><?php echo app('translator')->get("Netherlands"); ?></option>
<option value="Netherlands Antilles"><?php echo app('translator')->get("Netherlands Antilles"); ?></option>
<option value="New Caledonia"><?php echo app('translator')->get("New Caledonia"); ?></option>
<option value="New Zealand"><?php echo app('translator')->get("New Zealand"); ?></option>
<option value="Nicaragua"><?php echo app('translator')->get("Nicaragua"); ?></option>
<option value="Niger"><?php echo app('translator')->get("Niger"); ?></option>
<option value="Nigeria"><?php echo app('translator')->get("Nigeria"); ?></option>
<option value="Niue"><?php echo app('translator')->get("Niue"); ?></option>
<option value="Norfolk Island"><?php echo app('translator')->get("Norfolk Island"); ?></option>
<option value="Northern Mariana Islands"><?php echo app('translator')->get("Northern Mariana Islands"); ?></option>
<option value="Norway"><?php echo app('translator')->get("Norway"); ?></option>
<option value="Oman"><?php echo app('translator')->get("Oman"); ?></option>
<option value="Pakistan"><?php echo app('translator')->get("Pakistan"); ?></option>
<option value="Palau"><?php echo app('translator')->get("Palau"); ?></option>
<option value="Palestinian Territory, Occupied"><?php echo app('translator')->get("Palestinian Territory, Occupied"); ?></option>
<option value="Panama"><?php echo app('translator')->get("Panama"); ?></option>
<option value="Papua New Guinea"><?php echo app('translator')->get("Papua New Guinea"); ?></option>
<option value="Paraguay"><?php echo app('translator')->get("Paraguay"); ?></option>
<option value="Peru"><?php echo app('translator')->get("Peru"); ?></option>
<option value="Philippines"><?php echo app('translator')->get("Philippines"); ?></option>
<option value="Pitcairn"><?php echo app('translator')->get("Pitcairn"); ?></option>
<option value="Poland"><?php echo app('translator')->get("Poland"); ?></option>
<option value="Portugal"><?php echo app('translator')->get("Portugal"); ?></option>
<option value="Puerto Rico"><?php echo app('translator')->get("Puerto Rico"); ?></option>
<option value="Qatar"><?php echo app('translator')->get("Qatar"); ?></option>
<option value="Romania"><?php echo app('translator')->get("Romania"); ?></option>
<option value="Russia"><?php echo app('translator')->get("Russia"); ?></option>
<option value="Rwanda"><?php echo app('translator')->get("Rwanda"); ?></option>
<option value="Reunion"><?php echo app('translator')->get("Reunion"); ?></option>
<option value="Saint Barthelemy"><?php echo app('translator')->get("Saint Barthelemy"); ?></option>
<option value="Saint Helena, Ascension and Tristan Da Cunha"><?php echo app('translator')->get("Saint Helena, Ascension and Tristan Da Cunha"); ?></option>
<option value="Saint Kitts and Nevis"><?php echo app('translator')->get("Saint Kitts and Nevis"); ?></option>
<option value="Saint Lucia"><?php echo app('translator')->get("Saint Lucia"); ?></option>
<option value="Saint Martin"><?php echo app('translator')->get("Saint Martin"); ?></option>
<option value="Saint Pierre and Miquelon"><?php echo app('translator')->get("Saint Pierre and Miquelon"); ?></option>
<option value="Saint Vincent and the Grenadines"><?php echo app('translator')->get("Saint Vincent and the Grenadines"); ?></option>
<option value="Samoa"><?php echo app('translator')->get("Samoa"); ?></option>
<option value="San Marino"><?php echo app('translator')->get("San Marino"); ?></option>
<option value="Sao Tome and Principe"><?php echo app('translator')->get("Sao Tome and Principe"); ?></option>
<option value="Saudi Arabia"><?php echo app('translator')->get("Saudi Arabia"); ?></option>
<option value="Senegal"><?php echo app('translator')->get("Senegal"); ?></option>
<option value="Serbia"><?php echo app('translator')->get("Serbia"); ?></option>
<option value="Seychelles"><?php echo app('translator')->get("Seychelles"); ?></option>
<option value="Sierra Leone"><?php echo app('translator')->get("Sierra Leone"); ?></option>
<option value="Singapore"><?php echo app('translator')->get("Singapore"); ?></option>
<option value="Slovakia"><?php echo app('translator')->get("Slovakia"); ?></option>
<option value="Slovenia"><?php echo app('translator')->get("Slovenia"); ?></option>
<option value="Solomon Islands"><?php echo app('translator')->get("Solomon Islands"); ?></option>
<option value="Somalia"><?php echo app('translator')->get("Somalia"); ?></option>
<option value="South Africa"><?php echo app('translator')->get("South Africa"); ?></option>
<option value="South Sudan"><?php echo app('translator')->get("South Sudan"); ?></option>
<option value="South Georgia and the South Sandwich Islands"><?php echo app('translator')->get("South Georgia and the South Sandwich Islands"); ?></option>
<option value="Spain"><?php echo app('translator')->get("Spain"); ?></option>
<option value="Sri Lanka"><?php echo app('translator')->get("Sri Lanka"); ?></option>
<option value="Sudan"><?php echo app('translator')->get("Sudan"); ?></option>
<option value="Suriname"><?php echo app('translator')->get("Suriname"); ?></option>
<option value="Svalbard and Jan Mayen"><?php echo app('translator')->get("Svalbard and Jan Mayen"); ?></option>
<option value="Swaziland"><?php echo app('translator')->get("Swaziland"); ?></option>
<option value="Sweden"><?php echo app('translator')->get("Sweden"); ?></option>
<option value="Switzerland"><?php echo app('translator')->get("Switzerland"); ?></option>
<option value="Syrian Arab Republic"><?php echo app('translator')->get("Syrian Arab Republic"); ?></option>
<option value="Taiwan"><?php echo app('translator')->get("Taiwan"); ?></option>
<option value="Tajikistan"><?php echo app('translator')->get("Tajikistan"); ?></option>
<option value="Tanzania, United Republic of Tanzania"><?php echo app('translator')->get("Tanzania, United Republic of Tanzania"); ?></option>
<option value="Thailand"><?php echo app('translator')->get("Thailand"); ?></option>
<option value="Timor-Leste"><?php echo app('translator')->get("Timor-Leste"); ?></option>
<option value="Togo"><?php echo app('translator')->get("Togo"); ?></option>
<option value="Tokelau"><?php echo app('translator')->get("Tokelau"); ?></option>
<option value="Tonga"><?php echo app('translator')->get("Tonga"); ?></option>
<option value="Trinidad and Tobago"><?php echo app('translator')->get("Trinidad and Tobago"); ?></option>
<option value="Tunisia"><?php echo app('translator')->get("Tunisia"); ?></option>
<option value="Turkey"><?php echo app('translator')->get("Turkey"); ?></option>
<option value="Turkmenistan"><?php echo app('translator')->get("Turkmenistan"); ?></option>
<option value="Turks and Caicos Islands"><?php echo app('translator')->get("Turks and Caicos Islands"); ?></option>
<option value="Tuvalu"><?php echo app('translator')->get("Tuvalu"); ?></option>
<option value="Uganda"><?php echo app('translator')->get("Uganda"); ?></option>
<option value="Ukraine"><?php echo app('translator')->get("Ukraine"); ?></option>
<option value="United Arab Emirates"><?php echo app('translator')->get("United Arab Emirates"); ?></option>
<option value="United Kingdom"><?php echo app('translator')->get("United Kingdom"); ?></option>
<option value="United States"><?php echo app('translator')->get("United States"); ?></option>
<option value="Uruguay"><?php echo app('translator')->get("Uruguay"); ?></option>
<option value="Uzbekistan"><?php echo app('translator')->get("Uzbekistan"); ?></option>
<option value="Vanuatu"><?php echo app('translator')->get("Vanuatu"); ?></option>
<option value="Venezuela, Bolivarian Republic of Venezuela"><?php echo app('translator')->get("Venezuela, Bolivarian Republic of Venezuela"); ?></option>
<option value="Vietnam"><?php echo app('translator')->get("Vietnam"); ?></option>
<option value="Virgin Islands, British"><?php echo app('translator')->get("Virgin Islands, British"); ?></option>
<option value="Virgin Islands, U.S."><?php echo app('translator')->get("Virgin Islands, U.S."); ?></option>
<option value="Wallis and Futuna"><?php echo app('translator')->get("Wallis and Futuna"); ?></option>
<option value="Yemen"><?php echo app('translator')->get("Yemen"); ?></option>
<option value="Zambia"><?php echo app('translator')->get("Zambia"); ?></option>
<option value="Zimbabwe"><?php echo app('translator')->get("Zimbabwe"); ?></option><?php /**PATH D:\dev\vscode\resources\views/partials/country.blade.php ENDPATH**/ ?>